/**
 * Regenerate the README screenshots by driving the real sideye binary through VHS (a headless
 * terminal that renders Nerd Font icons correctly), so the icons and theme match a real terminal.
 * Each screen is a generated .tape that launches sideye, drives it to a state with keystrokes, and
 * screenshots it. The problems/diagnostics shots need a changed file with diagnostics, so a temp
 * errorful file is created in src/ around those runs only.
 *
 * Capture against a clean checkout so the tree and diff are representative — uncommitted files show
 * up in the captured tree. By default that's this repo; set `SIDEYE_SCREENSHOT_REPO` to point
 * sideye at another checkout (e.g. a clean main worktree) while the images still land in THIS
 * repo's assets. Requires `vhs` on PATH (brew install vhs) and a Nerd Font installed for the
 * file-type icons. Pass screen names to shoot a subset, e.g. `bun run screenshots find problems`.
 */
import { rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

/** Where the images are written (always this repo, so a PR here picks them up). */
const ASSETS = resolve(import.meta.dir, "../assets/screenshots");
/** Which checkout sideye runs against; override to capture a clean tree elsewhere. */
const REPO = process.env.SIDEYE_SCREENSHOT_REPO
  ? resolve(process.env.SIDEYE_SCREENSHOT_REPO)
  : resolve(import.meta.dir, "..");
const BUN = process.execPath;
const VHS = "vhs";
const TAPES = resolve(tmpdir(), "sideye-screenshots");
/** A few commits back so the diff and tree show several changed source files, not just a dep bump. */
const BASE_REF = "HEAD~3";
/**
 * Inside src/ so it falls under tsconfig's include and typescript-language-server reports the type
 * error alongside oxlint's unused-symbol findings.
 */
const FIXTURE = `${REPO}/src/_diagnostics-demo.ts`;

const header = [
  "Set Shell zsh",
  'Set FontFamily "FiraCode Nerd Font Mono"',
  "Set FontSize 28",
  "Set Width 2560",
  "Set Height 1520",
  "Set Padding 0",
  "Set Margin 0",
  "Set TypingSpeed 0",
].join("\n");

// VHS runs with cwd = the tmp tape dir, so cd into the capture target before launching sideye.
const launch = [
  "Hide",
  `Type "cd ${REPO} && ${BUN} run src/main.tsx ${BASE_REF}"`,
  "Enter",
  "Sleep 3s",
  "Show",
  "Sleep 500ms",
].join("\n");

/**
 * Open a real source-file diff (the palette focuses the viewer on select), so the main and find
 * shots feature code rather than the default docs file.
 */
const openDiffView = ["Ctrl+P", 'Type "DiffView"', "Sleep 400ms", "Enter", "Sleep 800ms"].join(
  "\n",
);

/**
 * One entry per README screenshot. `steps` run after the app is up; the end state is captured.
 * `fixture: true` marks screens that need the temporary diagnostics file planted first.
 */
const screens = [
  { name: "sideye", steps: openDiffView },
  { name: "worktree-picker", steps: ['Type "w"', "Sleep 800ms"].join("\n") },
  { name: "go-to-file", steps: ["Ctrl+P", 'Type "diff"', "Sleep 600ms"].join("\n") },
  {
    /**
     * Open the diff and let it focus/settle, then open the find bar and type a term present in the
     * visible hunks ("scrollTop"). Capture the open bar showing the live N/M counter and highlights
     * (the render test's verified checkpoint). No commit: a too-early `/` or a no-match Enter both
     * collapse back to a plain diff with no find UI, so generous settles and a real match matter.
     */
    name: "find",
    steps: [
      "Ctrl+P",
      'Type "DiffView"',
      "Sleep 500ms",
      "Enter",
      "Sleep 1500ms",
      'Type "/"',
      "Sleep 600ms",
      'Type "scrollTop"',
      "Sleep 1s",
    ].join("\n"),
  },
  { name: "search", steps: ["Ctrl+F", 'Type "Effect"', "Sleep 1200ms"].join("\n") },
  {
    // Open an unchanged file: plain syntax-highlighted source, no diff gutters.
    name: "read-only",
    steps: ["Ctrl+P", 'Type "process"', "Sleep 400ms", "Enter", "Sleep 800ms"].join("\n"),
  },
  { name: "keys", steps: ['Type "?"', "Sleep 600ms"].join("\n") },
  {
    // Open the fixture, open the panel, then wait out tsserver's project load (slower than oxlint).
    fixture: true,
    name: "problems",
    steps: [
      "Ctrl+P",
      'Type "diagnostics-demo"',
      "Sleep 400ms",
      "Enter",
      "Sleep 800ms",
      'Type "p"',
      "Sleep 16s",
    ].join("\n"),
  },
];

function tapeFor(screen: (typeof screens)[number]) {
  return [
    `# ${screen.name}.png — generated by script/screenshots.ts`,
    header,
    launch,
    screen.steps,
    // Written next to the tape in the tmp dir (VHS's cwd), then moved into ASSETS.
    `Screenshot ${screen.name}.png`,
    "",
  ].join("\n\n");
}

async function run(cmd: string, cmdArgs: string[]) {
  const proc = Bun.spawn([cmd, ...cmdArgs], {
    cwd: TAPES,
    stdio: ["inherit", "inherit", "inherit"],
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`${cmd} exited ${code}`);
  }
}

async function shoot(screen: (typeof screens)[number]) {
  await Bun.write(`${TAPES}/${screen.name}.tape`, tapeFor(screen));
  console.log(`▶ ${screen.name}`);
  await run(VHS, [`${TAPES}/${screen.name}.tape`]);
  await Bun.write(`${ASSETS}/${screen.name}.png`, Bun.file(`${TAPES}/${screen.name}.png`));
}

/** Sync so it can run from a signal handler before exit, not just the finally path. */
function removeFixture() {
  rmSync(FIXTURE, { force: true });
}

const only = new Set(Bun.argv.slice(2));
const unknown = [...only].filter((name) => !screens.some((screen) => screen.name === name));
if (unknown.length > 0) {
  console.warn(
    `ignoring unknown screen name(s): ${unknown.join(", ")} — known: ${screens.map((screen) => screen.name).join(", ")}`,
  );
}

const wanted = screens.filter((screen) => only.size === 0 || only.has(screen.name));
const standalone = wanted.filter((screen) => !screen.fixture);
const fixtured = wanted.filter((screen) => screen.fixture);

for (const screen of standalone) {
  // oxlint-disable-next-line no-await-in-loop -- vhs spawns a headless terminal; runs must be sequential
  await shoot(screen);
}

if (fixtured.length > 0) {
  /**
   * Diagnostics only exist for a changed file, so plant one. Lead with clean exported lines (no
   * findings, plain gutter) so the flagged lines' severity-colored gutter numbers stand out, then
   * tsc type errors (number = string) and oxc unused-symbol findings.
   */
  await Bun.write(
    FIXTURE,
    [
      "export function double(n: number) {",
      "  return n * 2",
      "}",
      "",
      'export const label: number = "oops"',
      "const ignored = double(label)",
      "const count: string = 42",
      "function helper(unusedParam: number) {}",
      "",
    ].join("\n"),
  );
  // A Ctrl-C mid-shoot skips the finally, so also delete the fixture on interruption.
  for (const signal of ["SIGINT", "SIGTERM"] as const) {
    process.once(signal, () => {
      removeFixture();
      process.exit(130);
    });
  }
  try {
    for (const screen of fixtured) {
      // oxlint-disable-next-line no-await-in-loop -- vhs spawns a headless terminal; runs must be sequential
      await shoot(screen);
    }
  } finally {
    removeFixture();
    console.log("cleaned up diagnostics fixture");
  }
}

console.log("done");
